language: node_js
sudo: false
cache:
  directories:
    - node_modules
    - app/bower_components
before_script:
  - npm install web-component-tester firebase-tools firebase-bolt
  - npm install bower
  - 'export PATH=$PWD/node_modules/.bin:$PATH'
  - bower install
node_js: 5
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - ./travis_runner.sh
