language: node_js
sudo: required
dist: trusty
cache:
  directories:
    - node_modules
    - app/bower_components
before_script:
  - npm install web-component-tester firebase-tools@2.2.1 firebase-bolt
  - npm install bower
  - 'export PATH=$PWD/node_modules/.bin:$PATH'
  - bower install
  - chmod +x ./travis_runner.sh
node_js: 5
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
      - ubuntu-toolchain-r-test
    packages:
      - google-chrome-stable
      - g++-4.8
script:
  - ./travis_runner.sh
env:
  global:
    - "CXX='g++-4.8'"
